name: PR Validation

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install htmlhint stylelint stylelint-config-standard --save-dev
      - name: Run HTMLHint
        run: npx htmlhint "src/**/*.html"
      - name: Run Stylelint
        run: npx stylelint "styles/**/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install parcel --save-dev
      - name: Build Project
        run: npx parcel build src/*.html
